<div id="header-top-banner">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <a href="#" id="close_banner">
                    <strong>X</strong>
                </a>
            </div>
        </div>
    </div>
</div>

<!-- <script>
    require([
        'jquery',
        'mage/cookies'
    ], function ($) {

        var cookName = 'header-top-banner';
        var cookVal = 'close_banner';
        
        $(document).on("click","#close_banner", function() {
            $.cookie(cookName, cookVal, { path: '/' });//Set the cookies
            document.getElementById("header-top-banner").style.display = "none";
        });

        var temp = $.cookie(cookName);//Get the cookies
        if(temp!=null){
            document.getElementById("header-top-banner").style.display = "none";
        }
    });
</script> -->